// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: budgets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (user_id, category_id, name, amount, period, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, category_id, name, amount, period, start_date, end_date, created_at, updated_at
`

type CreateBudgetParams struct {
	UserID     pgtype.UUID    `json:"user_id"`
	CategoryID pgtype.UUID    `json:"category_id"`
	Name       string         `json:"name"`
	Amount     pgtype.Numeric `json:"amount"`
	Period     string         `json:"period"`
	StartDate  pgtype.Date    `json:"start_date"`
	EndDate    pgtype.Date    `json:"end_date"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.UserID,
		arg.CategoryID,
		arg.Name,
		arg.Amount,
		arg.Period,
		arg.StartDate,
		arg.EndDate,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Amount,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets WHERE id = $1 AND user_id = $2
`

type DeleteBudgetParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteBudget(ctx context.Context, arg DeleteBudgetParams) error {
	_, err := q.db.Exec(ctx, deleteBudget, arg.ID, arg.UserID)
	return err
}

const getBudget = `-- name: GetBudget :one
SELECT id, user_id, category_id, name, amount, period, start_date, end_date, created_at, updated_at FROM budgets WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetBudgetParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetBudget(ctx context.Context, arg GetBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudget, arg.ID, arg.UserID)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Amount,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBudgets = `-- name: ListBudgets :many
SELECT id, user_id, category_id, name, amount, period, start_date, end_date, created_at, updated_at FROM budgets WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListBudgets(ctx context.Context, userID pgtype.UUID) ([]Budget, error) {
	rows, err := q.db.Query(ctx, listBudgets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Amount,
			&i.Period,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets
SET category_id = $3, name = $4, amount = $5, period = $6, end_date = $7, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, name, amount, period, start_date, end_date, created_at, updated_at
`

type UpdateBudgetParams struct {
	ID         pgtype.UUID    `json:"id"`
	UserID     pgtype.UUID    `json:"user_id"`
	CategoryID pgtype.UUID    `json:"category_id"`
	Name       string         `json:"name"`
	Amount     pgtype.Numeric `json:"amount"`
	Period     string         `json:"period"`
	EndDate    pgtype.Date    `json:"end_date"`
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudget,
		arg.ID,
		arg.UserID,
		arg.CategoryID,
		arg.Name,
		arg.Amount,
		arg.Period,
		arg.EndDate,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Amount,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
