// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: goals.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (user_id, name, target_amount, deadline)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, target_amount, current_amount, deadline, status, created_at, updated_at
`

type CreateGoalParams struct {
	UserID       pgtype.UUID    `json:"user_id"`
	Name         string         `json:"name"`
	TargetAmount pgtype.Numeric `json:"target_amount"`
	Deadline     pgtype.Date    `json:"deadline"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.UserID,
		arg.Name,
		arg.TargetAmount,
		arg.Deadline,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals WHERE id = $1 AND user_id = $2
`

type DeleteGoalParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) error {
	_, err := q.db.Exec(ctx, deleteGoal, arg.ID, arg.UserID)
	return err
}

const getGoal = `-- name: GetGoal :one
SELECT id, user_id, name, target_amount, current_amount, deadline, status, created_at, updated_at FROM goals WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetGoalParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetGoal(ctx context.Context, arg GetGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, getGoal, arg.ID, arg.UserID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGoals = `-- name: ListGoals :many
SELECT id, user_id, name, target_amount, current_amount, deadline, status, created_at, updated_at FROM goals WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListGoals(ctx context.Context, userID pgtype.UUID) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetAmount,
			&i.CurrentAmount,
			&i.Deadline,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET name = $3, target_amount = $4, deadline = $5, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, target_amount, current_amount, deadline, status, created_at, updated_at
`

type UpdateGoalParams struct {
	ID           pgtype.UUID    `json:"id"`
	UserID       pgtype.UUID    `json:"user_id"`
	Name         string         `json:"name"`
	TargetAmount pgtype.Numeric `json:"target_amount"`
	Deadline     pgtype.Date    `json:"deadline"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TargetAmount,
		arg.Deadline,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGoalProgress = `-- name: UpdateGoalProgress :one
UPDATE goals
SET current_amount = $3, status = $4, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, target_amount, current_amount, deadline, status, created_at, updated_at
`

type UpdateGoalProgressParams struct {
	ID            pgtype.UUID    `json:"id"`
	UserID        pgtype.UUID    `json:"user_id"`
	CurrentAmount pgtype.Numeric `json:"current_amount"`
	Status        string         `json:"status"`
}

func (q *Queries) UpdateGoalProgress(ctx context.Context, arg UpdateGoalProgressParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoalProgress,
		arg.ID,
		arg.UserID,
		arg.CurrentAmount,
		arg.Status,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
